### ISSUE TITLE
Documentation on how to manage MetaDeploy Admin Page (Step by Step)

### ISSUE THREAD

**Issue by ricxsar** [SFDO-Tooling/MetaDeploy#1090]
I was able to deploy the MetaDeploy on Heroku however I wasn't able to login using salesforce credentials when trying to install a product. It is somewhat related to `SocialApp`
```allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.```

I have created a social application with correct configurations I believe.
![image](https://user-images.githubusercontent.com/8968902/76921612-6e0a1c80-6909-11ea-8feb-dc04a018f263.png)

You can access the MetaDeploy in https://metadeploy-experiment.herokuapp.com/admin
Username: `admin`
Password: `password`

**Note: Don't worry about the app. It is for experiment anyways. Connected App is connected against a trailhead playground account**
```
2020-03-18T03:04:18.596337+00:00 heroku[router]: at=info method=GET path="/accounts/salesforce-production/login/?next=%2Fproducts%2Fcumulus-experiment%2F0ff6caa58a33370e62334c30485061f4f8a24aba%2Finstall" host=metadeploy-experiment.herokuapp.com request_id=34fb0cea-b5a6-4b39-aa1a-f8ee5bd5f55f fwd="119.93.144.173" dyno=web.1 connect=1ms service=107ms status=500 bytes=266 protocol=https
2020-03-18T03:04:18.591003+00:00 app[web.1]: ERROR Internal Server Error: /accounts/salesforce-production/login/
2020-03-18T03:04:18.591013+00:00 app[web.1]: Traceback (most recent call last):
2020-03-18T03:04:18.591014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-03-18T03:04:18.591015+00:00 app[web.1]:     response = get_response(request)
2020-03-18T03:04:18.591017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-03-18T03:04:18.591018+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-03-18T03:04:18.591019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-03-18T03:04:18.591019+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-03-18T03:04:18.591019+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 539, in wrapper
2020-03-18T03:04:18.591020+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2020-03-18T03:04:18.591020+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
2020-03-18T03:04:18.591021+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2020-03-18T03:04:18.591021+00:00 app[web.1]:   File "./metadeploy/multisalesforce/views.py", line 120, in dispatch
2020-03-18T03:04:18.591022+00:00 app[web.1]:     ret = super().dispatch(request, *args, **kwargs)
2020-03-18T03:04:18.591022+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 96, in dispatch
2020-03-18T03:04:18.591022+00:00 app[web.1]:     app = provider.get_app(self.request)
2020-03-18T03:04:18.591023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/providers/base.py", line 49, in get_app
2020-03-18T03:04:18.591023+00:00 app[web.1]:     return adapter.get_app(request, self.id)
2020-03-18T03:04:18.591023+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/adapter.py", line 203, in get_app
2020-03-18T03:04:18.591024+00:00 app[web.1]:     app = SocialApp.objects.get_current(provider, request)
2020-03-18T03:04:18.591024+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/models.py", line 32, in get_current
2020-03-18T03:04:18.591025+00:00 app[web.1]:     app = self.get(
2020-03-18T03:04:18.591026+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/manager.py", line 82, in manager_method
2020-03-18T03:04:18.591026+00:00 app[web.1]:     return getattr(self.get_queryset(), name)(*args, **kwargs)
2020-03-18T03:04:18.591026+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/db/models/query.py", line 406, in get
2020-03-18T03:04:18.591027+00:00 app[web.1]:     raise self.model.DoesNotExist(
2020-03-18T03:04:18.591027+00:00 app[web.1]: allauth.socialaccount.models.SocialApp.DoesNotExist: SocialApp matching query does not exist.
2020-03-18T03:04:18.592173+00:00 app[web.1]: id=34fb0cea-b5a6-4b39-aa1a-f8ee5bd5f55f at=INFO time="2020-03-18 03:04:18.591578" tag=external module=logging_middleware method=GET path=/accounts/salesforce-production/login/ status=500 source_ip=119.93.144.173 user_agent='Mozilla/5.0 (Windows=True NT=True 10.0;=True Win64;=True x64)=True AppleWebKit/537.36=True (KHTML,=True like=True Gecko)=True Chrome/80.0.3987.132=True Safari/537.36'=True time=0.08233094215393066 forwardedfor=119.93.144.173
2020-03-18T03:04:18.598013+00:00 app[web.1]: 10.142.64.122:22505 - - [18/Mar/2020:03:04:18] "GET /accounts/salesforce-production/login/?next=%2Fproducts%2Fcumulus-experiment%2F0ff6caa58a33370e62334c30485061f4f8a24aba%2Finstall" 500 27
```

**Comment by davisagli** [comment]
You don't need the "login.salesforce.com" site, but you do need to move the default site (labeled example.com) over to the "chosen sites" column to make sure the SocialApp is active.

**Comment by ricxsar** [comment]
@davisagli Still it doesn't redirect to login.salesforce.com when logging in as production. I think the path and query parameters are correct but the `Base URL` not pointing to the right place.
```
https://metadeploy-experiment.herokuapp.com/services/oauth2/authorize?client_id=3MVG9n_HvETGhr3Dt0csjHEUiRuw5sesEy7ZZeC.p99sr607o7ymmjojQNmOaB4A0qtb95KRXt_uVU3VZk7EQ&redirect_uri=https%3A%2F%2Fmetadeploy-experiment.herokuapp.com%2Faccounts%2Fsalesforce-production%2Flogin%2Fcallback%2F&scope=full+refresh_token+web&response_type=code&state=vwqYBMygtgEW&prompt=login
```
Maybe I will walk through what I'm doing since maybe I have a mistake during installation.
- App URL is `https://metadeploy-experiment.herokuapp.com/ `
- Connected App on Dev Hub
![image](https://user-images.githubusercontent.com/8968902/77024208-e4ba1f00-69c8-11ea-85be-a224ffd36710.png)

Creating the app on heroku. I'm not sure where should I get these. I'm assuming it is a salesforce connected app (Dev Hub account. I may be wrong). I'm not sure with the callback url.
![image](https://user-images.githubusercontent.com/8968902/77023794-c7d11c00-69c7-11ea-890a-8a352201afa5.png)

After creating the heroku app, I created a `Social Application` the same with the one I have entered on the installation step.
![image](https://user-images.githubusercontent.com/8968902/77024308-25b23380-69c9-11ea-9054-7a6c2a8505cb.png)

What should be the correct way (step by step) on configuring MetaDeploy?
Even just outline will be greatly appreciated.

**Comment by davisagli** [comment]
Set the SocialApp's Key to https://login.salesforce.com/

And the callback URL in the Heroku config var should be `https://metadeploy-experiment.herokuapp.com/accounts/salesforce-production/login/callback/` -- this needs to match one of the callback urls in the connected app.

**Comment by ricxsar** [comment]
How about test.salesforce.com? Should I created another connected app for it?

**Comment by davisagli** [comment]
For experiments and local testing I usually only set up the custom URL one. Then I can log into any org, though there's an extra step to paste in the custom domain.

Set up the production and test SocialApps if you want a shortcut to log into production and sandbox/scratch orgs without using the custom domain.

For a production copy of MetaDeploy you'll want all 3 since the login menu always shows them all.

**Comment by ricxsar** [comment]
Btw. I was able to login using production using the same Connected App with different SocialApp's key. Thanks for the heads up.

I notice an error when I try to deny the Oauth2 request.
```
id=b86949f4-2361-46f2-8ac1-8407489ceccb at=ERROR time="2020-03-19 02:37:58.155861" tag=external module=adapter msg="Social Account authentication error: (<AsgiRequest: GET '/accounts/salesforce-custom/login/callback/?error=access_denied&error_description=end-user+denied+authorization&state=nk1vgs6iwICt'>, 'salesforce-custom'), {'error': 'cancelled', 'exception': None, 'extra_context': {}}"
2020-03-19T02:37:58.156035+00:00 app[web.1]: 2020-03-19 02:37:58,155 ERROR    Social Account authentication error: (<AsgiRequest: GET '/accounts/salesforce-custom/login/callback/?error=access_denied&error_description=end-user+denied+authorization&state=nk1vgs6iwICt'>, 'salesforce-custom'), {'error': 'cancelled', 'exception': None, 'extra_context': {}}
2020-03-19T02:37:58.173053+00:00 app[web.1]: ERROR Internal Server Error: /accounts/salesforce-custom/login/callback/
2020-03-19T02:37:58.173055+00:00 app[web.1]: Traceback (most recent call last):
2020-03-19T02:37:58.173056+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-03-19T02:37:58.173057+00:00 app[web.1]:     response = get_response(request)
2020-03-19T02:37:58.173057+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
2020-03-19T02:37:58.173058+00:00 app[web.1]:     response = self.process_exception_by_middleware(e, request)
2020-03-19T02:37:58.173061+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
2020-03-19T02:37:58.173061+00:00 app[web.1]:     response = wrapped_callback(request, *callback_args, **callback_kwargs)
2020-03-19T02:37:58.173062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/hooks/framework_django.py", line 539, in wrapper
2020-03-19T02:37:58.173062+00:00 app[web.1]:     return wrapped(*args, **kwargs)
2020-03-19T02:37:58.173062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 73, in view
2020-03-19T02:37:58.173063+00:00 app[web.1]:     return self.dispatch(request, *args, **kwargs)
2020-03-19T02:37:58.173063+00:00 app[web.1]:   File "./metadeploy/multisalesforce/views.py", line 138, in dispatch
2020-03-19T02:37:58.173063+00:00 app[web.1]:     return super().dispatch(request, *args, **kwargs)
2020-03-19T02:37:58.173064+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/providers/oauth2/views.py", line 121, in dispatch
2020-03-19T02:37:58.173064+00:00 app[web.1]:     return render_authentication_error(
2020-03-19T02:37:58.173067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.8/site-packages/allauth/socialaccount/helpers.py", line 66, in render_authentication_error
2020-03-19T02:37:58.173068+00:00 app[web.1]:     get_adapter(request).authentication_error(
2020-03-19T02:37:58.173068+00:00 app[web.1]:   File "./metadeploy/multisalesforce/adapter.py", line 11, in authentication_error
2020-03-19T02:37:58.173069+00:00 app[web.1]:     raise kwargs["exception"]
2020-03-19T02:37:58.173069+00:00 app[web.1]: TypeError: exceptions must derive from BaseException
2020-03-19T02:37:58.178398+00:00 app[web.1]: id=b86949f4-2361-46f2-8ac1-8407489ceccb at=INFO time="2020-03-19 02:37:58.177805" tag=external module=logging_middleware method=GET path=/accounts/salesforce-custom/login/callback/ status=500 source_ip= user_agent='Mozilla/5.0 (Windows=True NT=True 10.0;=True Win64;=True x64)=True AppleWebKit/537.36=True (KHTML,=True like=True Gecko)=True Chrome/80.0.3987.132=True Safari/537.36'=True time=0.04751110076904297 forwardedfor= user=3pqVkgZ
```

**Comment by davisagli** [comment]
@ricxsar that one looks like a bug -- thanks for reporting

**Comment by ricxsar** [comment]
@davisagli Happy to help. :) I think this issue is resolved but better if you have comprehensive documentation on how to setup MetaDeploy.

**Comment by davisagli** [comment]
Yes, I agree. Not sure when we'll get to it, but we know it is needed!

**Comment by ricxsar** [comment]
Happy to close this.

**Comment by ricxsar** [comment]
Hi, @davisagli Sorry if I have too many questions.

I have manually added the steps when an error occurs on SFDO-Tooling/CumulusCI#1620.
https://metadeploy-experiment.herokuapp.com/products/cumulus-experiment/1.0/install

I'm trying to install it to a scratch org but it doesn't. I have already inspected on the scratch org `Deployment Status` but nothing in there. 

![image](https://user-images.githubusercontent.com/8968902/77036788-de3c9f00-69ea-11ea-9c5d-8a9e4f31159a.png)

The job is created successfully. 
![image](https://user-images.githubusercontent.com/8968902/77036875-0deba700-69eb-11ea-9c08-5670a9cbc08b.png)
 I also enabled all dynos.
![image](https://user-images.githubusercontent.com/8968902/77036932-26f45800-69eb-11ea-8048-a053d122a748.png)
Below are the logs when the job is queued I presume.
```
2020-03-19T05:52:30.287595+00:00 app[web.1]: id=none at=INFO time="2020-03-19 05:52:30.287259" tag=external module=push msg="Sending message {'type': 'notify', 'group': 'org.2f42bdc1b4761814efa095a6e4b5472af2403066', 'content': {'type': 'ORG_CHANGED', 'payload': {'current_job': OrderedDict([('id', '96qKv27'), ('product_slug', 'cumulus-experiment'), ('version_label', '1.0'), ('plan_slug', 'install'), ('plan_average_duration', None)]), 'current_preflight': None}}}"
2020-03-19T05:52:30.288049+00:00 app[web.1]: 2020-03-19 05:52:30,287 INFO     Sending message {'type': 'notify', 'group': 'org.2f42bdc1b4761814efa095a6e4b5472af2403066', 'content': {'type': 'ORG_CHANGED', 'payload': {'current_job': OrderedDict([('id', '96qKv27'), ('product_slug', 'cumulus-experiment'), ('version_label', '1.0'), ('plan_slug', 'install'), ('plan_average_duration', None)]), 'current_preflight': None}}}
2020-03-19T05:52:30.449910+00:00 app[web.1]: id=6a42c4b1-4492-482f-8df0-164fe76113d2 at=INFO time="2020-03-19 05:52:30.449243" tag=external module=logging_middleware method=POST path=/api/jobs/ status=201 source_ip= user_agent='Mozilla/5.0 (Windows=True NT=True 10.0;=True Win64;=True x64)=True AppleWebKit/537.36=True (KHTML,=True like=True Gecko)=True Chrome/80.0.3987.132=True Safari/537.36'=True time=1.1357569694519043 forwardedfor= user=3pqVkgZ
```

**Comment by davisagli** [comment]
There are several records that need to be added to the Repeatable Jobs section of the admin in order to start processing builds:

<img width="559" alt="Screen Shot 2020-03-19 at 9 30 59 AM" src="https://user-images.githubusercontent.com/49014/77072672-75dac700-69c4-11ea-9a0d-ad30394b4c38.png">
<img width="553" alt="Screen Shot 2020-03-19 at 9 31 09 AM" src="https://user-images.githubusercontent.com/49014/77072686-78d5b780-69c4-11ea-9020-6fc7cb2b603a.png">
<img width="554" alt="Screen Shot 2020-03-19 at 9 31 19 AM" src="https://user-images.githubusercontent.com/49014/77072693-7a9f7b00-69c4-11ea-87a0-14670714878c.png">

(In the future we'll hopefully set these up automatically.)

And you don't want all of the dyno types. Start with 1 web, 1 devworker, and 1 scheduler. Replace the devworker with 1 worker-short and multiple workers if you want to be able to run multiple installations in parallel. In #1089 I'm working on adjusting these to work like MetaCI so that there's an option to run with just 2 dynos.

**Comment by ricxsar** [comment]
@davisagli Metadeploy is now processing the installation however it reports installation failed. See the logs below. I also regenerated the Github Token and tried again but still the same error. Release version is also created https://github.com/ricxsar/cumulus-experiment/releases

```
2020-03-20T06:16:37.063339+00:00 app[worker.1]: id=none at=INFO time="2020-03-20 06:16:37.062860" tag=external module=push msg="Sending message {'type': 'notify', 'group': 'user.3pqVkgZ', 'content': {'type': 'BACKEND_ERROR', 'payload': {'message': 'There was an error'}}}"
2020-03-20T06:16:37.072620+00:00 app[worker.1]: id=none at=ERROR time="2020-03-20 06:16:37.072435" tag=external module=jobs msg="Traceback (most recent call last):
2020-03-20T06:16:37.072621+00:00 app[worker.1]:   File \"/app/metadeploy/api/jobs.py\", line 89, in report_errors_to
2020-03-20T06:16:37.072622+00:00 app[worker.1]:     yield
2020-03-20T06:16:37.072623+00:00 app[worker.1]:   File \"/app/metadeploy/api/jobs.py\", line 151, in run_flows
2020-03-20T06:16:37.072623+00:00 app[worker.1]:     repo = gh.repository(user, repo_name)
2020-03-20T06:16:37.072624+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/github3/github.py\", line 1981, in repository
2020-03-20T06:16:37.072624+00:00 app[worker.1]:     json = self._json(self._get(url), 200)
2020-03-20T06:16:37.072625+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/github3/models.py\", line 156, in _json
2020-03-20T06:16:37.072625+00:00 app[worker.1]:     raise exceptions.error_for(response)
2020-03-20T06:16:37.072626+00:00 app[worker.1]: github3.exceptions.NotFoundError: 404 Not Found
2020-03-20T06:16:37.072626+00:00 app[worker.1]: "
2020-03-20T06:16:37.076691+00:00 app[worker.1]: id=none at=ERROR time="2020-03-20 06:16:37.076542" tag=external module=jobs msg="job 152Ebq8 failed."
2020-03-20T06:16:37.129769+00:00 app[worker.1]: id=none at=INFO time="2020-03-20 06:16:37.129492" tag=external module=push msg="Sending message {'type': 'notify', 'group': 'org.2f42bdc1b4761814efa095a6e4b5472af2403066', 'content': {'type': 'ORG_CHANGED', 'payload': {'current_job': None, 'current_preflight': None}}}"
2020-03-20T06:16:37.143500+00:00 app[worker.1]: id=none at=INFO time="2020-03-20 06:16:37.143259" tag=external module=push msg="Sending message {'type': 'notify', 'group': 'job.152Ebq8', 'instance': {'model': 'job', 'id': '152Ebq8'}, 'serializer': 'metadeploy.api.serializers.JobSerializer', 'inner_type': 'JOB_FAILED'}"
2020-03-20T06:16:37.162967+00:00 app[worker.1]: id=no-job-id at=ERROR time="2020-03-20 06:16:37.162772" tag=external module=worker msg="github3.exceptions.NotFoundError: 404 Not Found
2020-03-20T06:16:37.162969+00:00 app[worker.1]: Traceback (most recent call last):
2020-03-20T06:16:37.162969+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/rq/worker.py\", line 884, in perform_job
2020-03-20T06:16:37.162970+00:00 app[worker.1]:     rv = job.perform()
2020-03-20T06:16:37.162971+00:00 app[worker.1]:   File \"/app/metadeploy/rq_worker.py\", line 12, in wrapper
2020-03-20T06:16:37.162971+00:00 app[worker.1]:     return orig(self)
2020-03-20T06:16:37.162972+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/rq/job.py\", line 664, in perform
2020-03-20T06:16:37.162972+00:00 app[worker.1]:     self._result = self._execute()
2020-03-20T06:16:37.162972+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/rq/job.py\", line 670, in _execute
2020-03-20T06:16:37.162973+00:00 app[worker.1]:     return self.func(*self.args, **self.kwargs)
2020-03-20T06:16:37.162973+00:00 app[worker.1]:   File \"/app/metadeploy/api/jobs.py\", line 151, in run_flows
2020-03-20T06:16:37.162973+00:00 app[worker.1]:     repo = gh.repository(user, repo_name)
2020-03-20T06:16:37.162974+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/github3/github.py\", line 1981, in repository
2020-03-20T06:16:37.162974+00:00 app[worker.1]:     json = self._json(self._get(url), 200)
2020-03-20T06:16:37.162974+00:00 app[worker.1]:   File \"/app/.heroku/python/lib/python3.8/site-packages/github3/models.py\", line 156, in _json
2020-03-20T06:16:37.162975+00:00 app[worker.1]:     raise exceptions.error_for(response)
2020-03-20T06:16:37.162979+00:00 app[worker.1]: github3.exceptions.NotFoundError: 404 Not Found
2020-03-20T06:16:37.162980+00:00 app[worker.1]: "
```



I don't know if this is a bug. The connection of the org is apparently lost but when I refresh the page, I'm still logged in. It's not yet 10 minutes for the token to expire but metadeploy reports that it is already expired.
![image](https://user-images.githubusercontent.com/8968902/77140302-296eb480-6ab4-11ea-980a-dc6c445c2055.png)

When I visit the installation page on a new tab, it asks me to log in but on the user icon, I am still logged in.
![image](https://user-images.githubusercontent.com/8968902/77140588-0b558400-6ab5-11ea-86b7-a4bf75a4eb14.png)

**Comment by davisagli** [comment]
Repo url should be https://github.com/ricxsar/cumulus-experiment without the .git suffix. Also double check that your Personal Access Token includes the "repo" scope.

It's intentional that the access token for the org is deleted after the job completes (whether success or failure), as a security precaution to avoid holding credentials longer than necessary. We should probably end the user's Django session at that point too to avoid confusion.

**Comment by ricxsar** [comment]
@davisagli I was able to deploy it on a scratch org. Thanks for the help.

**Comment by snehaheda** [comment]
@ricxsar @davisagli I am trying to use metadeploy. I added products & OAuth working. Plan published. But I am still not able to see my products on the UI. Any pointers.

URL - https://package-installer.herokuapp.com/products
