### ISSUE TITLE
Metadeploy publish will fail if there is tag prefix

### ISSUE THREAD

**Issue by rodolforicojr** [SFDO-Tooling/MetaDeploy#3568]
Metadeploy version: Latest

Replication Steps:

1. cci task run github_release --version=0.2 --package_type=2GP --tag_prefix=rel/
2. cci task run github_release_notes --tag rel/0.2

<img width="1202" alt="image" src="https://github.com/user-attachments/assets/158808af-e90b-44f7-8a8a-1fc76c6d855f">

3. cci task run metadeploy_publish --tag rel/0.2
<img width="919" alt="image" src="https://github.com/user-attachments/assets/901b873b-dc8e-42fb-b8af-535f0b3fbcf4">

Error Logs: https://gist.github.com/rodolforicojr/fb80f653aeebc5e913e9878e5d39f5e3

Manually creating the version via admin will fail
<img width="764" alt="image" src="https://github.com/user-attachments/assets/bb944777-2613-4109-8ca9-fc56cc7e2bb4">

**Comment by yippie** [comment]
@rodolforicojr if you are publishing a tag, you need to use `--tag rel/0.2` to publish, not --commit, the commit is expecting a hash key only.

In addition, your prefix might need to match one of the configured prefix_beta or prefix_release items in the cumulusCI file at project->git

**Comment by rodolforicojr** [comment]
Its been a while but I got a chance to look into this again. The suggestion is working as expected. I just noticed one behaviour.

When there is already existing versions, it the metadeploy_publish will refer to the first item on the version list even though I have specified the tag name. 

It should be ID: b7KmXrd  and not ID: 90rMRKB. This will cause to return 400

<img width="1167" height="844" alt="Image" src="https://github.com/user-attachments/assets/2b675034-6a82-4f12-9896-1323a289f8df" />

Command: ```cci task run metadeploy_publish -o tag rel/0.5```

```
cci task run metadeploy_publish -o tag rel/0.5 --debug
[07/20/25 09:12:59] DEBUG    Added rich.logging.RichHandler to logger: urllib3                                                                                          logger.py:53
[07/20/25 09:12:59] INFO     Beginning task: Publish                                                                                                                    tasks.py:235
                    INFO                                                                                                                                                tasks.py:239
                    DEBUG    Starting new HTTPS connection (1): alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443                                            connectionpool.py:1019
[07/20/25 09:13:01] DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET                                                                   connectionpool.py:474
                             /admin/rest/products?repo_url=https%3A%2F%2Fgithub.com%2Frodolforicojr%2FXXXXXXX HTTP/1.1" 200 680                        
                    DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET /admin/rest/versions?product=pRE7DrD HTTP/1.1" 200 1040           connectionpool.py:474
[07/20/25 09:13:01] INFO     Found https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/versions/90rMRKB                                              metadeploy.py:319
                    DEBUG    Starting new HTTPS connection (1): api.github.com:443                                                                            connectionpool.py:1019
[07/20/25 09:13:03] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXXX/git/ref/tags/rel/0.5 HTTP/1.1" 200 None connectionpool.py:474
[07/20/25 09:13:04] DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXXX/git/tags/d14ed084bb31c985968e2fbad79f6af208cbe2f1 HTTP/1.1" 200 None                         
[07/20/25 09:13:04] INFO     Downloading commit bdc9c4c46d6722c318a39f88b320046cf2233d6f of rodolforicojr/XXXXXXX from GitHub         metadeploy.py:130
[07/20/25 09:13:05] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXX/zipball/bdc9c4c46d6722c318a39f88b320046cf2233d6f HTTP/1.1" 302 0                             
                    DEBUG    Starting new HTTPS connection (1): codeload.github.com:443                                                                       connectionpool.py:1019
[07/20/25 09:13:06] DEBUG    https://codeload.github.com:443 "GET                                                                                              connectionpool.py:474
                             /rodolforicojr/XXXXXXXXX/legacy.zip/bdc9c4c46d6722c318a39f88b320046cf2233d6f?token=XXXXXX                      
                             UVA3IPRB42 HTTP/1.1" 200 499233                                                                                                                        
[07/20/25 09:13:10] WARNING  Optional dependencies are missing. Handling high volumes of records for the 'select' functionality will be significantly slower, as  select_utils.py:24
                             optimizations for this feature are currently disabled. To enable optimized performance, install all required dependencies using:                       
                             pipx upgrade cumulusci[select]                                                                                                                         
                                                                                                                                                                                    
[07/20/25 09:13:11] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
[07/20/25 09:13:12] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXX/releases/latest HTTP/1.1" 200 None      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXX/git/ref/tags/rel/0.5 HTTP/1.1" 200 None connectionpool.py:474
[07/20/25 09:13:13] DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXXXgit/tags/d14ed084bb31c985968e2fbad79f6af208cbe2f1 HTTP/1.1" 200 None                         
                    DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXX/contents/cumulusci.yml?ref=bdc9c4c46d6722c318a39f88b320046cf2233d6f                          
                             HTTP/1.1" 200 None                                                                                                                                                                                                                                       
[07/20/25 09:13:14] DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET /admin/rest/plantemplates?product=pRE7DrD&name=install HTTP/1.1"  connectionpool.py:474
                             200 391                                                                                                                                                
[07/20/25 09:13:14] INFO     Found https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/plantemplates/34                                              metadeploy.py:342
                    DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "POST /admin/rest/plans HTTP/1.1" 400 72                               connectionpool.py:474

Traceback (most recent call last):
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/cli/cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/cli/task.py", line 180, in run_task
    task()
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/tasks.py", line 226, in __call__
    self.result = self._run_task()
                  ^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/tasks/metadeploy.py", line 158, in _run_task
    self._publish_plan(product, version, plan_name, plan_config, steps)
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/tasks/metadeploy.py", line 258, in _publish_plan
    plan = self.api.create_plan(plan=plan_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/metadeploy/api.py", line 60, in create_plan
    return self._create("/plans", plan)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/metadeploy/api.py", line 42, in _create
    return safe_json_from_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/utils/http/requests_utils.py", line 12, in safe_json_from_response
    response.raise_for_status()
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/plans
```

**Comment by rodolforicojr** [comment]
Its been a while but I got a chance to look into this again. The suggestion is working as expected. I just noticed one behaviour.

When there is already existing versions, it the metadeploy_publish will refer to the first item on the version list even though I have specified the tag name. 

It should be ID: b7KmXrd  and not ID: 90rMRKB. This will cause to return 400

<img width="1167" height="844" alt="Image" src="https://github.com/user-attachments/assets/2b675034-6a82-4f12-9896-1323a289f8df" />

Command: ```cci task run metadeploy_publish -o tag rel/0.5```

```
cci task run metadeploy_publish -o tag rel/0.5 --debug
[07/20/25 09:12:59] DEBUG    Added rich.logging.RichHandler to logger: urllib3                                                                                          logger.py:53
[07/20/25 09:12:59] INFO     Beginning task: Publish                                                                                                                    tasks.py:235
                    INFO                                                                                                                                                tasks.py:239
                    DEBUG    Starting new HTTPS connection (1): alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443                                            connectionpool.py:1019
[07/20/25 09:13:01] DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET                                                                   connectionpool.py:474
                             /admin/rest/products?repo_url=https%3A%2F%2Fgithub.com%2Frodolforicojr%2FFundraising-Advanced-NPC-Accelerator HTTP/1.1" 200 680                        
                    DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET /admin/rest/versions?product=pRE7DrD HTTP/1.1" 200 1040           connectionpool.py:474
[07/20/25 09:13:01] INFO     Found https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/versions/90rMRKB                                              metadeploy.py:319
                    DEBUG    Starting new HTTPS connection (1): api.github.com:443                                                                            connectionpool.py:1019
[07/20/25 09:13:03] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXXX/git/ref/tags/rel/0.5 HTTP/1.1" 200 None connectionpool.py:474
[07/20/25 09:13:04] DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXXX/git/tags/d14ed084bb31c985968e2fbad79f6af208cbe2f1 HTTP/1.1" 200 None                         
[07/20/25 09:13:04] INFO     Downloading commit bdc9c4c46d6722c318a39f88b320046cf2233d6f of rodolforicojr/XXXXXXX from GitHub         metadeploy.py:130
[07/20/25 09:13:05] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXX/zipball/bdc9c4c46d6722c318a39f88b320046cf2233d6f HTTP/1.1" 302 0                             
                    DEBUG    Starting new HTTPS connection (1): codeload.github.com:443                                                                       connectionpool.py:1019
[07/20/25 09:13:06] DEBUG    https://codeload.github.com:443 "GET                                                                                              connectionpool.py:474
                             /rodolforicojr/XXXXXXXXX/legacy.zip/bdc9c4c46d6722c318a39f88b320046cf2233d6f?token=XXXXXX                      
                             UVA3IPRB42 HTTP/1.1" 200 499233                                                                                                                        
[07/20/25 09:13:10] WARNING  Optional dependencies are missing. Handling high volumes of records for the 'select' functionality will be significantly slower, as  select_utils.py:24
                             optimizations for this feature are currently disabled. To enable optimized performance, install all required dependencies using:                       
                             pipx upgrade cumulusci[select]                                                                                                                         
                                                                                                                                                                                    
[07/20/25 09:13:11] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXX HTTP/1.1" 200 None                      connectionpool.py:474
[07/20/25 09:13:12] DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXX/releases/latest HTTP/1.1" 200 None      connectionpool.py:474
                    DEBUG    https://api.github.com:443 "GET /repos/rodolforicojr/XXXXXXXXXX/git/ref/tags/rel/0.5 HTTP/1.1" 200 None connectionpool.py:474
[07/20/25 09:13:13] DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXXXXgit/tags/d14ed084bb31c985968e2fbad79f6af208cbe2f1 HTTP/1.1" 200 None                         
                    DEBUG    https://api.github.com:443 "GET                                                                                                   connectionpool.py:474
                             /repos/rodolforicojr/XXXXXXXXX/contents/cumulusci.yml?ref=bdc9c4c46d6722c318a39f88b320046cf2233d6f                          
                             HTTP/1.1" 200 None                                                                                                                                                                                                                                       
[07/20/25 09:13:14] DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "GET /admin/rest/plantemplates?product=pRE7DrD&name=install HTTP/1.1"  connectionpool.py:474
                             200 391                                                                                                                                                
[07/20/25 09:13:14] INFO     Found https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/plantemplates/34                                              metadeploy.py:342
                    DEBUG    https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com:443 "POST /admin/rest/plans HTTP/1.1" 400 72                               connectionpool.py:474

Traceback (most recent call last):
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/cli/cci.py", line 91, in main
    cli(args[1:], standalone_mode=False, obj=runtime)
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/cli/task.py", line 180, in run_task
    task()
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/tasks.py", line 226, in __call__
    self.result = self._run_task()
                  ^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/tasks/metadeploy.py", line 158, in _run_task
    self._publish_plan(product, version, plan_name, plan_config, steps)
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/tasks/metadeploy.py", line 258, in _publish_plan
    plan = self.api.create_plan(plan=plan_json)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/metadeploy/api.py", line 60, in create_plan
    return self._create("/plans", plan)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/core/metadeploy/api.py", line 42, in _create
    return safe_json_from_response(response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/cumulusci/utils/http/requests_utils.py", line 12, in safe_json_from_response
    response.raise_for_status()
  File "/Users/rodolforico/.local/pipx/venvs/cumulusci/lib/python3.12/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://alphasys-metadeploy-e1e9a1b41417.herokuapp.com/admin/rest/plans
```
