### ISSUE TITLE
500 Server Error when authorizing with a user lacking Modify All Data

### ISSUE THREAD

**Issue by davidmreed** [SFDO-Tooling/MetaDeploy#903]
When authorizing to MetaDeploy via a user who does not have the Modify All Data permission, a 500 server error results. The stack trace runs:

```
2020-01-29T23:21:17.970828+00:00 app[web.2]: Traceback (most recent call last):
2020-01-29T23:21:17.970829+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
2020-01-29T23:21:17.970830+00:00 app[web.2]:     response = get_response(request)
2020-01-29T23:21:17.970833+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
2020-01-29T23:21:17.970834+00:00 app[web.2]:     response = self.process_exception_by_middleware(e, request)
2020-01-29T23:21:17.970835+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
2020-01-29T23:21:17.970836+00:00 app[web.2]:     response = response.render()
2020-01-29T23:21:17.970837+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/response.py", line 106, in render
2020-01-29T23:21:17.970838+00:00 app[web.2]:     self.content = self.rendered_content
2020-01-29T23:21:17.970839+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/response.py", line 83, in rendered_content
2020-01-29T23:21:17.970840+00:00 app[web.2]:     content = template.render(context, self._request)
2020-01-29T23:21:17.970841+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/backends/django.py", line 61, in render
2020-01-29T23:21:17.970842+00:00 app[web.2]:     return self.template.render(context)
2020-01-29T23:21:17.970843+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 171, in render
2020-01-29T23:21:17.970844+00:00 app[web.2]:     return self._render(context)
2020-01-29T23:21:17.970845+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/newrelic/api/function_trace.py", line 130, in dynamic_wrapper
2020-01-29T23:21:17.970846+00:00 app[web.2]:     return wrapped(*args, **kwargs)
2020-01-29T23:21:17.970847+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 163, in _render
2020-01-29T23:21:17.970848+00:00 app[web.2]:     return self.nodelist.render(context)
2020-01-29T23:21:17.970849+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-01-29T23:21:17.970850+00:00 app[web.2]:     bit = node.render_annotated(context)
2020-01-29T23:21:17.970851+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-01-29T23:21:17.970852+00:00 app[web.2]:     return self.render(context)
2020-01-29T23:21:17.970853+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/defaulttags.py", line 309, in render
2020-01-29T23:21:17.970854+00:00 app[web.2]:     return nodelist.render(context)
2020-01-29T23:21:17.970855+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 937, in render
2020-01-29T23:21:17.970856+00:00 app[web.2]:     bit = node.render_annotated(context)
2020-01-29T23:21:17.970857+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 904, in render_annotated
2020-01-29T23:21:17.970858+00:00 app[web.2]:     return self.render(context)
2020-01-29T23:21:17.970859+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 987, in render
2020-01-29T23:21:17.970860+00:00 app[web.2]:     output = self.filter_expression.resolve(context)
2020-01-29T23:21:17.970861+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/template/base.py", line 698, in resolve
2020-01-29T23:21:17.970862+00:00 app[web.2]:     new_obj = func(obj, *arg_vals)
2020-01-29T23:21:17.970863+00:00 app[web.2]:   File "./metadeploy/api/templatetags/api_bootstrap.py", line 13, in serialize
2020-01-29T23:21:17.970864+00:00 app[web.2]:     return escape(json.dumps(FullUserSerializer(user).data))
2020-01-29T23:21:17.970865+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/rest_framework/serializers.py", line 562, in data
2020-01-29T23:21:17.970866+00:00 app[web.2]:     ret = super().data
2020-01-29T23:21:17.970867+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/rest_framework/serializers.py", line 260, in data
2020-01-29T23:21:17.970868+00:00 app[web.2]:     self._data = self.to_representation(self.instance)
2020-01-29T23:21:17.970869+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/rest_framework/serializers.py", line 516, in to_representation
2020-01-29T23:21:17.970870+00:00 app[web.2]:     attribute = field.get_attribute(instance)
2020-01-29T23:21:17.970871+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/rest_framework/fields.py", line 454, in get_attribute
2020-01-29T23:21:17.970872+00:00 app[web.2]:     return get_attribute(instance, self.source_attrs)
2020-01-29T23:21:17.970873+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/rest_framework/fields.py", line 94, in get_attribute
2020-01-29T23:21:17.970874+00:00 app[web.2]:     instance = getattr(instance, attr)
2020-01-29T23:21:17.970875+00:00 app[web.2]:   File "/app/.heroku/python/lib/python3.8/site-packages/django/utils/functional.py", line 257, in inner
2020-01-29T23:21:17.970876+00:00 app[web.2]:     return func(self._wrapped, *args)
2020-01-29T23:21:17.970877+00:00 app[web.2]:   File "./metadeploy/api/models.py", line 196, in valid_token_for
2020-01-29T23:21:17.970878+00:00 app[web.2]:     if all(self.token) and self.org_id:
2020-01-29T23:21:17.970879+00:00 app[web.2]:   File "./metadeploy/api/models.py", line 149, in org_id
2020-01-29T23:21:17.970880+00:00 app[web.2]:     return self._get_org_property("Id")
2020-01-29T23:21:17.970881+00:00 app[web.2]:   File "./metadeploy/api/models.py", line 143, in _get_org_property
2020-01-29T23:21:17.970882+00:00 app[web.2]:     return self.social_account.extra_data[ORGANIZATION_DETAILS][key]
2020-01-29T23:21:17.970883+00:00 app[web.2]: TypeError: 'NoneType' object is not subscriptable

**Comment by davisagli** [comment]
Added a better error message in #956
